/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package motoca;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Comunix
 */
public class Principal extends javax.swing.JFrame {
    Motoca mPesq = null;
    static ArrayList<Motoca> motocas = new ArrayList();
    
    // Relatorios rel=null;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        diretoNoCodigo();
        tfCor.setEnabled(false);
        cbxVolt.setEnabled(false);
    }
    
    public void diretoNoCodigo(){
        Motoca.setpBasico(100);
        motocas.add(new Motoca(101, "Monica"));
        motocas.add(new Motoca(102, "Cascao"));
        motocas.add(new MotocaE(103, "Cebolinha","220"));
        motocas.add(new MotocaE(104, "Magali","220"));
        motocas.add(new MotocaC(105, "Monica","Azul"));
        motocas.add(new MotocaC(106, "Cascao","Verde"));
        
        limpar();
    }
    

    public Motoca existeCodigo(int codigo) {
        for (Motoca m : motocas) {
            if (m.getCod() == codigo) {
                return m;
            }
        }
        return null;
    }

    public void incluir() {
        if(tfCod.getText().equals("")||cbxPerso.getSelectedIndex()==0)
            System.out.println("Você deve preencher os campos código e personagem");
        else{
            if (existeCodigo(Integer.parseInt(tfCod.getText())) != null) {
                JOptionPane.showMessageDialog(null, "Código já cadastrado!");
            } else {
                if (rbComum.isSelected()) 
                    motocas.add(new Motoca(Integer.parseInt(tfCod.getText()), cbxPerso.getSelectedItem().toString()));
                 else if (rbEletrica.isSelected()) 
                    motocas.add(new MotocaE(Integer.parseInt(tfCod.getText()), cbxPerso.getSelectedItem().toString(), cbxVolt.getSelectedItem().toString()));
                 else 
                    motocas.add(new MotocaC(Integer.parseInt(tfCod.getText()), cbxPerso.getSelectedItem().toString(), tfCor.getText()));

                System.out.println(motocas.toString());
               
            }   
        }
    }
    
    public void report(){
        
    }   
    
    public void pesquisar(){
        
        if(tfCod.getText().equals("")) 
            System.out.println("Digite o código do item que deseja pesquisar!");
        
        else{
            mPesq = existeMotoca(Integer.parseInt(tfCod.getText()));
            if(mPesq == null)
                System.out.println("Código não cadastrado");
            else{
                cbxPerso.setSelectedItem(mPesq.getPersonagem());
                if (mPesq instanceof MotocaC){
                    tfCor.setEnabled(true);
                    tfCor.setText(( (MotocaC) mPesq).getCor());
                    rbCober.setSelected(true);
                }
                else if (mPesq instanceof MotocaE) {
                    cbxVolt.setEnabled(true);
                    cbxVolt.setSelectedItem(((MotocaE)mPesq).getVoltagem());
                    rbEletrica.setSelected(true);
                }
                
                else
                    rbComum.setSelected(true);
            }
        }
        btnInserir.setEnabled(false);
        btnPesquisar.setEnabled(false);        
        btnExcluir.setEnabled(true); 
        
    }
    
    public void limpar() {
        tfCod.setText(null);
        tfCor.setText(null);
        cbxVolt.setSelectedIndex(0);
        cbxPerso.setSelectedIndex(0);
        rbComum.setSelected(true);
    
    }
    
    public Motoca existeMotoca(int cod){
        for (Motoca m : motocas)
            if (m.getCod() == cod)
                return m;
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbComum = new javax.swing.JRadioButton();
        rbEletrica = new javax.swing.JRadioButton();
        rbCober = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCod = new javax.swing.JTextField();
        cbxPerso = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxVolt = new javax.swing.JComboBox();
        btnInserir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfCor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rbComum);
        rbComum.setSelected(true);
        rbComum.setText("Comum");
        rbComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbComumActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbEletrica);
        rbEletrica.setText("Elétrica");
        rbEletrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEletricaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCober);
        rbCober.setText("Cobertura");
        rbCober.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCoberActionPerformed(evt);
            }
        });

        jLabel1.setText("Cadastro de Motoca");

        jLabel2.setText("Tipo de Motoca:");

        jLabel3.setText("Código: ");

        cbxPerso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Monica", "Cebolinha", "Cascao", "Magali" }));
        cbxPerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPersoActionPerformed(evt);
            }
        });

        jLabel4.setText("Personagem: ");

        jLabel5.setText("Voltagem: ");

        cbxVolt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "110", "220" }));

        btnInserir.setText("Incluir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel6.setText("Cor: ");

        jButton1.setText("Alterar Preço Básico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Relatórios");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);
        taSaida.getAccessibleContext().setAccessibleName("Saida: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(147, 147, 147)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbComum)
                                    .addGap(27, 27, 27)
                                    .addComponent(rbEletrica)
                                    .addGap(35, 35, 35)
                                    .addComponent(rbCober))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfCod, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfCor)))
                                    .addGap(54, 54, 54)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cbxVolt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cbxPerso, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnPesquisar)
                                            .addGap(14, 14, 14)
                                            .addComponent(jToggleButton1))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(154, 154, 154)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCober)
                    .addComponent(rbEletrica)
                    .addComponent(rbComum)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxPerso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxVolt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnPesquisar)
                    .addComponent(btnExcluir)
                    .addComponent(jToggleButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbComumActionPerformed
        tfCor.setEnabled(false);
        cbxVolt.setEnabled(false);
    }//GEN-LAST:event_rbComumActionPerformed

    private void rbCoberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCoberActionPerformed
        cbxVolt.setEnabled(false);
        tfCor.setEnabled(true);
    }//GEN-LAST:event_rbCoberActionPerformed

    private void cbxPersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPersoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPersoActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        incluir();
        limpar();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void rbEletricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEletricaActionPerformed
        cbxVolt.setEnabled(true);
        tfCor.setEnabled(false);
    }//GEN-LAST:event_rbEletricaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         double pBasico = Double.parseDouble(JOptionPane.showInputDialog("Preço Básico:"));
        Motoca.setpBasico(pBasico);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        motocas.remove(mPesq);
        limpar();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
         pesquisar();
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        report();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbxPerso;
    private javax.swing.JComboBox cbxVolt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton rbCober;
    private javax.swing.JRadioButton rbComum;
    private javax.swing.JRadioButton rbEletrica;
    private javax.swing.JTextArea taSaida;
    private javax.swing.JTextField tfCod;
    private javax.swing.JTextField tfCor;
    // End of variables declaration//GEN-END:variables
}
